### ISSUE TITLE
Kalman filter G and u problems

### ISSUE THREAD

**Issue by rlabbe** [rlabbe/filterpy#1]
1. the predict() method takes in an optional parameter u instead of using KalmanFilter.u variable. There is no way to get the object's u to be used. This can be worked around if you are calling predict, but batch_filter will always ignore KalmanFilter.u.

2. I have constrained G to be of a certain size depending  on the dim_u parameter. However it is perfectly legal for G to be a scalar such as 1. The constraint should not be that G or u be of a specific size, but only that Gu is of the same size as the state vector. There is no reasonable way to constrain that in the setters, so let it go and accept that there will be an exception thrown in predict() if the user got it wrong.

**Comment by Dugucloud** [comment]
@rlabbe Err, I think in a mechanical system, gravity Gy can be a part of state transition Fx. Because even the control u is zero, it still affects the state x.

**Comment by rlabbe** [comment]
u is no longer a member of KalmanFilter, so OBE.
