### ISSUE TITLE
UKF does not support missing data as 'None'

### ISSUE THREAD

**Issue by isaacyeaton** [rlabbe/filterpy#10]
In the doc string to `UnscentedKalmanFilter.batch_filter`, it states to represent missing data as `None`. However, this fails in the update step with a type multiply error; there appears to be no code to handle this case. In the standard `KalmanFilter.update`, there is a simple return statement if `z` is `None`.

**Comment by rlabbe** [comment]
Good catch.

I will be updating the unscented KFs classes soon; hopefully this weekend. I will incorporate this change then.

**Comment by rlabbe** [comment]
This should be fixed.
