### ISSUE TITLE
Probably lack of dimensions in Q_discrete_white_noise from discretization.py

### ISSUE THREAD

**Issue by Prokhozhijj** [rlabbe/filterpy#101]
Hi, Roger,

First of all, thanks for you work. It is great and very useful.

Now to my problem. I'am trying to use 4x4 function with UKF (see the code below, please) and due to that reason I'd like to generate proper white noise for its Q matrix. But there is a limitation (only 2 or 3 dimensions can be used for that). 

Is it possible to extend Q_discrete_white_noise to use 4 dimensions? Actually I am rather practitioner, not a theoretic. So your help with that would be appreciated. Thanks. 

>         
        def f_Fj(x, dt):
            dt2 = dt * dt
            dt3 = dt2 * dt
            A = np.array ([[1, dt, dt2/2, dt3/6],
                           [0, 1,  dt,    dt2/2],
                           [0, 0,  1,     dt],
                           [0, 0,  0,     1]])
            return A.dot(x)

**Comment by Prokhozhijj** [comment]
It looks like I have found the solution for my problem (see formula 21 on the URL below).

[https://core.ac.uk/download/pdf/11603388.pdf](url)

Can you add it to your code?

**Comment by Prokhozhijj** [comment]
Never mind. Please ignore this request.

**Comment by rlabbe** [comment]
Released in 1.2.4
