### ISSUE TITLE
Failure to handle when np.dot returns scalar rather than ndarray

### ISSUE THREAD

**Issue by dkloving** [rlabbe/filterpy#104]
In the KalmanFilter update function, Hx is computed as np.dot(H, x) which will return a scalar if both H and x are 1-D arrays. This causes Hx to have shape () and ndim 0, leading to AssertionError when comparing its shape to z.

Issue can be reproduced with the example code at https://filterpy.readthedocs.io/en/latest/kalman/KalmanFilter.html

**Comment by rlabbe** [comment]
I cannot duplicate with the example code.

I do not see an assert on the shape of z in the code except in the function test_matrix_dimensions, which is not called unless you do so explicitly.

Can you provide an exact code example that reproduces and the exact assert text?

**Comment by dkloving** [comment]
I can't reproduce it today either. I think that I must have been unintentionally somehow calling test_matrix_dimensions, because that's the assertion that was failing. It must have been user error somewhere. Sorry for the false alert.

**Comment by dkloving** [comment]
I can't reproduce it today either. I think that I must have been unintentionally somehow calling test_matrix_dimensions, because that's the assertion that was failing. It must have been user error somewhere. Sorry for the false alert.
