### ISSUE TITLE
ValueError in unscented_transform

### ISSUE THREAD

**Issue by Prokhozhijj** [rlabbe/filterpy#129]
I'm trying to use UKF in 1d mode.

Filter's initialization:
```
self._dim_x = 3
self._points = MerweScaledSigmaPoints(n = self._dim_x, alpha = 0.001, beta = 2., kappa = 0.)
```

After initialization:

`
self._points.Wm.shape = (7,)
`

And after calling UKF.batch_filter I am getting:

```
   File "g:\proj\python\filterpy\filterpy\kalman\UKF.py", line 596, in batch_filter
    self.update(z, r, UT=UT)
  File "g:\proj\python\filterpy\filterpy\kalman\UKF.py", line 434, in update
    zp, Pz = UT(self.sigmas_h, self.Wm, self.Wc, R, self.z_mean, self.residual_z)
  File "g:\proj\python\filterpy\filterpy\kalman\unscented_transform.py", line 104, in unscented_transform
    x = np.dot(Wm, sigmas)    # dot = \Sigma^n_1 (W[k]*Xi[k])
ValueError: shapes (7,) and (1,7) not aligned: 7 (dim 0) != 1 (dim 0)
```

It looks like this is because of the following code in UKF.update()

`
self.sigmas_h = np.atleast_2d(sigmas_h)
`

**Comment by rlabbe** [comment]
I don't understand your example. You say "1d", yet dimension x to be 3. The value error states: shapes (7,) and (1,7), which implies that the shape of x is 1.

**Comment by Prokhozhijj** [comment]
I'm tracking position, velocity and acceleration for an object with one dimension. So according to the comment to UKF dim_x should be 3. Am I wrong?

**Comment by rlabbe** [comment]
Sorry, didn't notice this has the h sigmas. 

I need to see source code. The shape of sigmas_h should be (7, 1), not (1, 7)

**Comment by Kexin-Wei** [comment]
met the same issue, also using UKF to predict a 1d nonlinear motion, for future people coming here for solutions, be aware of your `hx` return, need to be a numpy array, like `np.array([z])`
