### ISSUE TITLE
Remove dependency on Matplotlib

### ISSUE THREAD

**Issue by prensing** [rlabbe/filterpy#148]
Unfortunately, it looks like you cannot use the standard filter classes without pulling in Matplotlib. For instance, I imported the UKF class from Kalman and got an error because my computer does not have tkinter (used as a graphics driver by matplotlib). The dependence is coming from stats, I believe. 

Thanks for the work, and I love the book.

**Comment by rlabbe** [comment]
The dependency remains, but FilterPy will only import matplotlib if you call one of the plotting functions.
