### ISSUE TITLE
Offtopic: Which Kalman Filter to use?

### ISSUE THREAD

**Issue by schnickn** [rlabbe/filterpy#149]
Your book has a lot of useful information, so nice work so far! 

As I'm brand new to Kalman Filtering, I was wondering if you could suggest an area or appropriate Kalman Filter that I could use for a question I have?

I have a pandas df with index as Temperature (x) and a column Intensity (y), the baseline region (typically the temperature region from 25-32) is often noisy. I'm trying to output the temperature (Tonset) at which the Intensity just starts to increase (something like 4 standard deviations above the 'baseline').

Here's an example of a typical data curve:
https://i0.wp.com/research.csiro.au/crystal/wp-content/uploads/sites/75/2017/03/DSF-Curve.jpg?resize=780%2C633&ssl=1
It's at the bottom of the page...the temperature output for this example would be ~44.

Any help would be much appreciated!

**Comment by rlabbe** [comment]
I'd look at the adaptive filtering chapter. I'd implement a constant velocity filter (assumes intensity doesn't change, in other words). Then, run it, and look at the Mahalanobis distance after every call to update(). Mahalanobis is the standard deviation error, so set your limit to 4:

    for i in intensity:
         kf.predict()
         kf.update(i)
         if kf.mahalanobis > 4:
              do_something

Something like that.

**Comment by schnickn** [comment]
Great...I'll have a look at it. Thanks for steering me in the right direction!
