### ISSUE TITLE
Is there a way to update only certain values of Z?

### ISSUE THREAD

**Issue by joaqo** [rlabbe/filterpy#150]
Hey, just started using the library and I'm finding it super useful. There's just one thing I haven't been able to figure out. I am using a kalman filter which has a Z that agglomerates several sensors, but they are not all updated at the same time, some are updated more frequently than others. 

I want to know if I can update only some on each update step. I tried setting the ones I dont wan't to update to `nan` but I don't think thats working correctly.

Thanks!

**Comment by rlabbe** [comment]
You have to think it through based on what you are trying to do. Predict just predicts via your plant model, update incorporates a measurement by comparing the error to the prediction at that same time step. You may, for example, need to alter F in the input to predict() to account for the different time steps between measurements, and you may need to alter H on every call to update based on which sensor you are using. In pseudo code it might read

# get sensor 1
F = compute_f(dt)
kf.predict()
kf.update(z1, R=R1, H=H1)

#get sensor 2
F = compute_f(dt)
kf.predict()
kf.update(z2, R=R2, H=H2)

# get sensor 2 again
F = compute_f(dt)
kf.predict()
kf.update(z2, R=R2, H=H2)

and so on.

**Comment by joaqo** [comment]
That makes a lot of sense? Thanks!
