### ISSUE TITLE
Documentation for `sigma_points` in `unscented_transform`

### ISSUE THREAD

**Issue by goretkin** [rlabbe/filterpy#152]
Documentation for `sigma_points` appears to be outdated:
https://github.com/rlabbe/filterpy/blob/bfad77c12df846308a58a002c3be83db60288b74/filterpy/kalman/unscented_transform.py#L34

The current usage appears to be this:
https://github.com/rlabbe/filterpy/blob/6649409da39c61ea401ac241aaa2feeb976647a4/filterpy/kalman/sigma_points.py#L146

**Comment by rlabbe** [comment]
Well, those are equivalent statements in that #sigmas per dimension == n, and dimension == 2n+1. I don't think there is anything that *requires* the UT to use 2n+1, it is just the implementation chosen for UKF sigma points. So, the UT documentation is a bit more general. 

I think the confusing thing is [#sigmas per dimension, dimension]  is using 'dimension' in two different ways. The first means the problem dimension, the second means the array dimension. So, the documentation needs to change, I'm not sure on the wording yet.

**Comment by goretkin** [comment]
Isn't `#sigmas per dimension` == 2 , not `n` ?

**Comment by rlabbe** [comment]
Oh, I see what you are saying, of course.

**Comment by rlabbe** [comment]
Fixed.
