### ISSUE TITLE
Bug in LeastSquaresFilter.update (least_squares.py)

### ISSUE THREAD

**Issue by Prokhozhijj** [rlabbe/filterpy#154]
It looks like something is wrong with the code below. self.n should not be incremented 'cos for relatively large amount of data (more than several thousand elements) there is a tendency for increasing divergence between source data and filter's output.

```
     def update(self, z):
         """ Update filter with new measurement `z` """
 
         self.n += 1
```

**Comment by rlabbe** [comment]
n is the count of the number of updates. You have to increment it. Perhaps you have come across some other bug, but this is not the cause.

**Comment by Prokhozhijj** [comment]
I was trying to comment that increment, and only after that everything worked as expected.

**Comment by rlabbe** [comment]
It had nothing to do with n, it was not using the derivatives of the states to compute the residual and new states. I've checked in a fix.

**Comment by Prokhozhijj** [comment]
The issue still exists and it is related to "n" incrementing.

**Comment by rlabbe** [comment]
I cannot fix a bug that is not reported in a way that I can duplicate it.

There is no way incrementing n is the bug. You may be able to mask the problem by commenting it out or something, but the entire algorithm is based on computing the regression based on the number of updates. Incrementing n is correct.

**Comment by Prokhozhijj** [comment]
"For the data with, for example, twenty thousand elements, the more "n, the more divergence I'm getting at the end of my sample. I don't think this is correct. But when "n" has fixed value there is large divergence in the very beginning until algorithm is warming up but after everything looks good.

**Comment by rlabbe** [comment]
I need actual source code/data, not a vague statement. For example, this code runs perfectly, and this is two million elements:

    xs = [i+randn() for i in range(2000000)]
    lsq= LeastSquaresFilter(dt=1, order=1)

    ys = [lsq.update(x)[0] for x in xs]

    plt.plot(xs)
    plt.plot(ys)

I suspect your data is not linear. This is a pretty dumb class that does a linear regression recursively, and probably doesn't belong in FilterPy. In other words, it is always just going to draw a straight line through your data. If your data doesn't form a straight line, it won't give very good results.

**Comment by Prokhozhijj** [comment]
I'm sorry for boring. But there is my test case if you have time for it.

Data:

[foo.zip](https://github.com/rlabbe/filterpy/files/2291479/foo.zip)

Code:

```
import numpy as np
from filterpy.leastsq import LeastSquaresFilter
import matplotlib.pyplot as plt
import pandas as pd

lsq = LeastSquaresFilter(dt=1, order=1)
xs = pd.read_csv("foo.csv").values
ys = np.array([lsq.update(x)[0] for x in xs])

delta = xs - ys

plt.plot(xs)
plt.plot(ys)
plt.show()
```

**Comment by rlabbe** [comment]
Hi, thanks, now I can investigate this properly!

I ran the code and the output looked about like I would expect. To test this, I ran the Matlab code from Zarchan's book which also implements this algorithm on your data. The results are identical. In the image below the Matlab output is on the left and the Python/FilterPy is on the right.

LSQ is just not a good algorithm for signals like your data. You would use LSQ order 1 to extract a straight line from very noisy data. And, there is really no point in that, you would just run a linear regression. The filter can track a 'slightly' nonlinear signal, but it will always lag it. This is just a 'toy' filter that has no place in any serious application, in my opinion. A Kalman filter will always do better. 

I think by fixing N to a constant you turned it into a type of fading or fixed memory filter, which probably let it adapt to local changes in the signal better. You can google those filters for more information. But I'm not really aware of any reason to use those filters these days when we have superior filters (I may be wrong in that assertion, I haven't paid that much attention to this aspect of filtering, as I've always needed Kalman/particle filters in my personal work).

I'll give you a chance to respond, then close this out if there are no objections, or you can close it if you like.

![image](https://user-images.githubusercontent.com/5308143/44186339-b4fcb400-a0cd-11e8-87d0-6ba0364eb88d.png)

**Comment by Prokhozhijj** [comment]
Ok, thanks for your time.
