### ISSUE TITLE
Mahalanobis distance calculation

### ISSUE THREAD

**Issue by christopherfish** [rlabbe/filterpy#155]
`kalman_filter.py:mahalanobis():`
`    _mahalanobis = float(np.dot(np.dot(self.y.T, self.SI), self.y)))`

Unless I'm very much mistaken, Wikipedia [[Mahalanobis distance](https://en.wikipedia.org/wiki/Mahalanobis_distance)], and the first couple of other sources on Google, all define the Mahalanobis distance as the square root of the above calculation. Is this deliberate (and if so, should it be documented), are there multiple conventions around, or am I just misunderstanding something?

PS. thank you for your wonderful work on this library and the associated book. It has been incredibly helpful!

**Comment by rlabbe** [comment]
Egads! You are of course correct.

**Comment by rlabbe** [comment]
Fixed.
