### ISSUE TITLE
Support different dimension of observations

### ISSUE THREAD

**Issue by KevinWangTHU** [rlabbe/filterpy#160]
https://github.com/rlabbe/filterpy/blob/b8a6629f7d3a1255dbf2ea82ba4b7e98c672cfd3/filterpy/kalman/kalman_filter.py#L525

It fixed the dimension of observation. If we pass in an `H` of different observation dimension, the code would break.

**Comment by rlabbe** [comment]
I went to so much trouble trying to make this class accept things like lists or scalars, and it is just a pain, with lurking bugs like this. I'm probably going to get rid of all of this specialized code, and require all inputs to be 2d arrays.
