### ISSUE TITLE
KalmanFilter's get_prediction not handle B=None

### ISSUE THREAD

**Issue by KuangyeChen** [rlabbe/filterpy#169]
https://github.com/rlabbe/filterpy/blob/582885dd9e01c2784a5786b02fb527b46f090370/filterpy/kalman/kalman_filter.py#L1001

It's weird, because it's handled in the _predict_ method.
This method should just be a copy of _predict_ without altering self.x

**Comment by rlabbe** [comment]
While I agree, I think I prefer removing all of these get_ methods. I don't use this style of programming in the rest of the library, and there are the stand alone functions update() and predict() if you want to compute a value without altering the object. 

I'm in the process of converting to 3.5+, which will be a breaking change, so I think I will make the change on that check in to minimize churn.
