### ISSUE TITLE
Support state-dependent noise?

### ISSUE THREAD

**Issue by ngbrenda** [rlabbe/filterpy#182]
If I have a state transition function where the noise term is scaled by the state:
   `x[t] = f(x[t-1]) + f(x[t-1])*N(0,sigma)`
Will your implementation of ukf still work? It's not obvious from the documentation since all your example f() and h() lack noise.

**Comment by rlabbe** [comment]
That's not how noise works. The attribute R implements measurement noise, and Q implements process nose. Both are in the examples, and my book explains all of this in detail.
