### ISSUE TITLE
NESS -> NEES misspelling

### ISSUE THREAD

**Issue by armavox** [rlabbe/filterpy#185]
https://github.com/rlabbe/filterpy/blob/8123214de798ffb63db968bb0b9492ee74e77950/filterpy/stats/stats.py#L1137

**Comment by jonathanjfshaw** [comment]
Yup. Which conflicts with 08-Designing-Kalman-Filters.ipynb where we have `from filterpy.stats import NEES`

**Comment by rlabbe** [comment]
Fixed.
