### ISSUE TITLE
Matrices not aligned in `KalmanFilter.update_correlated`

### ISSUE THREAD

**Issue by MichaelMauderer** [rlabbe/filterpy#187]
The function `KalmanFilter.update_correlated` contains the following line ([line 735](https://github.com/rlabbe/filterpy/blob/8123214de798ffb63db968bb0b9492ee74e77950/filterpy/kalman/kalman_filter.py#L735)):
` self.S = dot(H, PHT) + dot(H, self.M) + dot(self.M.T, H.T) + R`

However it seems that the matrices in the second and third term don't match up.

`H` has the form `dim_z x dim_x` (according to its [initialization](https://github.com/rlabbe/filterpy/blob/8123214de798ffb63db968bb0b9492ee74e77950/filterpy/kalman/kalman_filter.py#L410))
`M` has the form `dim_z x dim_z`  (according to its [initialization](https://github.com/rlabbe/filterpy/blob/8123214de798ffb63db968bb0b9492ee74e77950/filterpy/kalman/kalman_filter.py#L413))

That means that both `dot(H, self.M) ` and `dot(self.M.T, H.T) ` do not work as matrix multiplications. 

This mismatch also appears as a exception when running the test `test_kf.test_z_dim` and replacing `update` with `update_correlated`:
```
>       self.S = dot(H, PHT) + dot(H, self.M) + dot(self.M.T, H.T) + R
E       ValueError: shapes (1,2) and (1,1) not aligned: 2 (dim 1) != 1 (dim 0)
```

**Comment by rlabbe** [comment]
I checked in vhartman's fix. Thanks!
