### ISSUE TITLE
EKF `update` function do not update SI attribute

### ISSUE THREAD

**Issue by atrabattoni** [rlabbe/filterpy#188]
It looks to me that the SI attribut should be updated in the `update` function in a equal way as in the `predict_update` function. This is not a big issue but prevents mahalanobis distance measurements.

EKf.py line 235
```python
        self.S = dot(H, PHT) + R
        self.SI = linalg.inv(self.S)
        self.K = dot(PHT, self.SI)
```
EKf.py line 320
```python
        self.S = dot(H, PHT) + R
        self.K = PHT.dot(linalg.inv(self.S))
```

EKF.py line 408
```python
            self._mahalanobis = sqrt(float(dot(dot(self.y.T, self.SI), self.y)))
```

**Comment by rlabbe** [comment]
This is fixed. Thanks!

**Comment by nwesem** [comment]
@rlabbe I see that this was fixed in the merge, but it doesn't seem to be in the current version `1.4.5`.  I think the computation of `self.SI` needs to be added again to the `update` function. Maybe it was lost in a later merge..
