### ISSUE TITLE
KalmanFilter for sensor fusion

### ISSUE THREAD

**Issue by songshan0321** [rlabbe/filterpy#191]
I have multiple sensors giving the same measurement vector but with different frequency.
So I do predict() and update() when i receive sensor 1, and only do update() when i receive sensor 2 measurement. e.g. update(), update(), predict(), update(), update(), predict().

But the kf.x sometimes is correct dimension, sometimes is not. How can I solve this problem?

**Comment by vhartman** [comment]
Do you have a more concrete example? (Ideally the minimum needed to recreate the error)

**Comment by rlabbe** [comment]
closed for lack of follow up.
