### ISSUE TITLE
How can I add or subtract a constant within observation equation?

### ISSUE THREAD

**Issue by james-trimarco** [rlabbe/filterpy#195]
Thanks for the amazing library and book! It's one of the best resources for learning state-space filtering.

I'm currently using a Kalman filter to estimate energy use within a building. I have an observation vector of zs that represent the outside air temperature. I'm trying to create a model that uses _the difference_ between the hidden variable `inside_temp` and a constant variable `thermostat_setting` to estimate energy use. 

So state equation:

$inside_temp_{t+1} = F(inside_temp)+ B(outside_temp)$

measurement equation:

$y_i = H(thermostat_setting - inside_temp)$

Right now we have just a single variable y_i so the model is pretty simple (`dim_x=1, dim_y=1`). I just can't figure out how to get the subtraction in the measurement equation to work. Does `filterpy` support adding or subtracting a constant before multiplication by the H matrix?

**Comment by rlabbe** [comment]
I'm not entirely sure I understand; I will answer as if I do!

The hidden variable needs to be part of the state so the KF can estimate it, and the process model needs to compute the inside temp. So you would take the thermometer setting as a control input, compute how much heat/cooling is applied to the system, adjust it by how much heat is transferred through the outside walls to get the new inside temperature.

Thus your state would end up being something like [outside_temp, inside_temp, insulation_coefficients]


Then H is pretty simple. Your measurement is nothing more than the outside temperature, so H shapes the state X to extract only the outside temp.

I'm dubious this construction is of much value. You need a very detailed process model of how your heater and/or AC operates, and perhaps the heat loss model is complicated as well (I have no idea if you could just model it as a constant - I would assume in general heat moves slowly, and so, say, the roof leaking heat will depend on how quickly that region gets heated).

**Comment by RoyLarson** [comment]
I don't think this is possible using the math
My first thought was that this would be possible but

```
y = H@x

# if 
H = [[thermastat_setting, -inside_temp]] 
# and 
x = [
    [ inside_temp ],
    [ inside_temp ]
]
# then the matrix multiplication would work but the answer would be thermastat_setting*inside_temp - inside_temp**2
# but 
x = [[ inside_temp ]] 
# so you get a matrix multiplication error
```

Also I think you are violating some of the assumptions in the KalmanFilter by trying to 
use the current state in the measurement transformation matrix.  I have tried that before and it always  
failed on me, and then I realized that my formulation was improper when working through the math

for your case
```
outside_temp = (thermastat_setting - inside_temp)*inside_temp
outside_temp = thermastat_setting*inside_temp - inside_temp**2
``` 
which I don't think you actually intend to do that but given what you stated is what you would end up with.
