### ISSUE TITLE
Dealing with angles in the UKF

### ISSUE THREAD

**Issue by offirk** [rlabbe/filterpy#197]
Hi,
I'm trying to implement a UKF that fuses several sensors, among them a gyroscope.
in the UKF there is a special treatment for the calculation of the residual in the case of angle measurements, by allowing to define a specific subtraction function (since it is not a regular 'linear' subtraction). however, in the update function final step, the addition of the residual (times K, the gain) to the state vector X, there is no such option and the addition is a regular arithmetic addition.
am I missing something here?
thanks, Offir

**Comment by rlabbe** [comment]
I've added state_add attribute to the class to support this.

**Comment by beetleskin** [comment]
Don't we have to do the same within rts_smoothing? https://github.com/rlabbe/filterpy/blob/master/filterpy/kalman/UKF.py#L734
