### ISSUE TITLE
module 'filterpy' has no attribute 'monte_carlo'

### ISSUE THREAD

**Issue by aslanfth** [rlabbe/filterpy#200]
I installed the package using pip, when I try to use filterpy.monte_carlo.residual_resample it gives the error in the title.

**Comment by jlandmann** [comment]
Just go ahead and try:

`from filterpy.monte_carlo import residual_resample`

and see if that works for you.

**Comment by rlabbe** [comment]
That's a good workaround, but I have to fix my __init_.py to make the request possible (you should be able to do that).

**Comment by rlabbe** [comment]
fixed
