### ISSUE TITLE
KalmanFilter.batch_filter fails when first observation is None

### ISSUE THREAD

**Issue by felixlaumon** [rlabbe/filterpy#21]
````py
zs = [None, 0.5, 0.25]
kf.batch_filter(zs)
# AttributeError: 'NoneType' object has no attribute 'ndim'
````

I suppose this is because https://github.com/rlabbe/filterpy/blob/master/filterpy/kalman/kalman_filter.py#L348 tries to check the `zs` dim with the first observation which in this case in None?

**Comment by rlabbe** [comment]
The code tries to check that the values in zs are valid by looking at the first element. So if the first element is None havoc ensues.

I'll issue a fix soon. In the meantime, if this is not just a test case, you can just delete the following lines from KalmanFilter.batch_filter()

        try:
            z = zs[0]
        except:
            assert not isscalar(zs), 'zs must be list-like'

        if self.dim_z == 1:
            assert isscalar(z) or (z.ndim==1 and len(z) == 1), \
            'zs must be a list of scalars or 1D, 1 element arrays'

        else:
            assert len(z) == self.dim_z, 'each element in zs must be a'
            '1D array of length {}'.format(self.dim_z)

**Comment by rlabbe** [comment]
This has been fixed, and is tested for in the unit test test_batch_filter() in test_kf.py.

**Comment by felixlaumon** [comment]
Thanks!
