### ISSUE TITLE
How to use batch_filter, and rts_smoother for multiple sensors with different sampling rates

### ISSUE THREAD

**Issue by bcordo** [rlabbe/filterpy#22]
Thanks for this amazing library coupled with your very informative book. I am really grateful that you spent so much time making this great. 

In you book you have an [example](https://github.com/rlabbe/Kalman-and-Bayesian-Filters-in-Python/blob/master/08-Designing-Kalman-Filters.ipynb) of creating a filter that could handle measurements from two sensors with different sampling frequencies. The solution there was to create different R and H matrices depending on which sensor we have at a particular time. 

My question is how we can do this but using the batch_filter, and rts_smoother functions? Is that already implemented in filterPy and I just missed that, or do you have a recommended way to implement this myself.

Thanks so much. 

Best,

Brad

**Comment by rlabbe** [comment]
It is not built into the library, unfortunately. You can pass in a
list of Rs, but not Hs, to batch_filter. I would kind of like to add
this, just haven't gotten to it yet.


Just look at the code for batch_filter and rts. They are just loops.
Write your own loops, and substitute in your own R and H at the
appropriate places.

I know that is a brief answer; if you have more questions just ask.


On 9/8/15, Brad Cordova <notifications@github.com> wrote:
> Thanks for this amazing library coupled with your very informative book. I
> am really grateful that you spent so much time making this great.
>
> In you book you have an
> [example](https://github.com/rlabbe/Kalman-and-Bayesian-Filters-in-Python/blob/master/08-Designing-Kalman-Filters.ipynb)
> of creating a filter that could handle measurements from two sensors with
> different sampling frequencies. The solution there was to create different R
> and H matrices depending on which sensor we have at a particular time.
>
> My question is how we can do this but using the batch_filter, and
> rts_smoother functions? Is that already implemented in filterPy and I just
> missed that, or do you have a recommended way to implement this myself.
>
> Thanks so much.
>
> Best,
>
> Brad
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/rlabbe/filterpy/issues/22


-- 


  )..(
  (.o)
`.(  )
  ||||
  "`'"

**Comment by bcordo** [comment]
Great thanks so much for the quick response. Will try that now. 

Brad
