### ISSUE TITLE
Bounded solutions for Kalman Filter Estimates

### ISSUE THREAD

**Issue by mbronzo** [rlabbe/filterpy#220]
Hi to everyone!
First of all I would like to thank you a lot for the amazing work done, it was incredibly useful, even for someone like me, inexperienced about the topics. 
My issue regard the possibility of bounding the estimates of x so that each term in the vector is non-negative, as my real life variables should not be negative.
I have seen different ways to tackle this issue, one resorted to the Extended version of the filter associating to the original state x an augmented state that uses a sigmoid function. Nevertheless I have seen the possibility of implementing such constraints in the original version of the Kalman Filter ("Kalman filtering with state constraints: a survey of linear and nonlinear algorithms", D. Simon[2009]).
I was wondering whether there is any possibility of implementing such constraints in the Kalman Filter directly from the Filterpy library, and in case there's not, if you could suggest which way I should go for.

Thank you again for your time and patience.

**Comment by mbronzo** [comment]
I solved this issue, thanks again for the amazing library!

**Comment by wqp89324** [comment]
@mbronzo how did you solve this issue?

**Comment by mbronzo** [comment]
@wqp89324 I restated the initial linear constrained model into a non linear one and used the Unscented Kalman Filter. Not sure can be done in any case but for my model specification a softmax did the job.
