### ISSUE TITLE
pykalman to filterpy

### ISSUE THREAD

**Issue by tzhern** [rlabbe/filterpy#223]
Hi, does anybody know how to write this code in filterpy? I tried to move to filterpy as it is still being developed. I find it quite hard to understand the parameters. I am not sure whether the observation matrices is H or R or anything else

==================================
from pykalman import KalmanFilter

# Construct a Kalman filter
    kf = KalmanFilter(  transition_matrices = [1],
                        observation_matrices = [1],
                        initial_state_mean = 0,
                        observation_covariance = 1,
                        transition_covariance = 0.01)

    state_means, _ = kf.filter(x.values)
    state_means = pd.Series(state_means.flatten(), index = x.index)
====================================

where x.values is just 1 d array (e.g list(1,2,3,4,5)

I'll appreciate a lot

**Comment by tartakovsky** [comment]
Hi. Had the same question some time ago. It helped me a lot to actually read through the [book](https://github.com/rlabbe/Kalman-and-Bayesian-Filters-in-Python/) @rlabbe wrote. 

I don't have the code handy, but here is the param mapping and the approximate functional implementation (re-check the array shapes). Hope you can figure out the rest. If not – definitely read the book :)

```
def kalman_ma_batch(zs, x, P, Q, R=1., F=1., H=1.):
    """
    Parameters
    ----------
    zs: observations, (x.values in your code)
    x: initial mean estimate, e.g. = x.values[0]
    P: initial covariance estimate, e.g. = 1.
    Q: process noise (transition covariance), tuning parameter
    R: measurement noise (observation covariance), default = 1.
    F: transition matrix, default = 1.
    H: measurement (observation) matrix, default = 1.
    return_all: flag to control which variables to return
    
    Returns
    -------
    (x_posts, P_posts), same as (state_means, state_covariances) in PyKalman
    """
    
    xs = np.atleast_1d(x)
    Ps = np.eye(xs.shape[0])*P
    Fs = np.full(zs.shape[0], F)
    Qs = np.full(zs.shape[0], Q)
    Hs = np.full(zs.shape[0], H)
    Rs = np.full(zs.shape[0], R)
    
    x_posts, P_posts, _, _ = batch_filter(xs, Ps, zs, Fs, Qs, Hs, Rs)
    return x_posts.flatten(), P_posts.flatten()
```

```
Usage:
state_means, _ = kalman_ma_batch(x.values, 0., 1., Q=0.01)
```

**Comment by rlabbe** [comment]
I'm not sure what the confusion is. From Ipython, 

    KalmanFilter?

will produce the help for this class In it you will see H is the measurement function, R is the measurement noise. It also contains a pretty complete example of what you are trying to achieve.  Is the issue nomenclature? Unfortunately the Kalman filter literature is not consistent, and I apparently chose different sources than pykalman. In any case, as suggested my book is the documentation for this project. 

One thing the project perhaps lacks is an 'intermediate' tutorial for someone that understands Kalman filters and just wants to use the library. It was never created because I didn't develop FilterPy as a stand alone library; I just created it as I wrote the book. It really isn't meant as a standalone project, though it has turned into that for many people.

**Comment by rlabbe** [comment]
I pushed a change, incorporating additional nomenclature for the various matrices.

**Comment by tzhern** [comment]
> I'm not sure what the confusion is. From Ipython,
> 
> ```
> KalmanFilter?
> ```
> 
> will produce the help for this class In it you will see H is the measurement function, R is the measurement noise. It also contains a pretty complete example of what you are trying to achieve. Is the issue nomenclature? Unfortunately the Kalman filter literature is not consistent, and I apparently chose different sources than pykalman. In any case, as suggested my book is the documentation for this project.
> 
> One thing the project perhaps lacks is an 'intermediate' tutorial for someone that understands Kalman filters and just wants to use the library. It was never created because I didn't develop FilterPy as a stand alone library; I just created it as I wrote the book. It really isn't meant as a standalone project, though it has turned into that for many people.



> Hi @tzhern. Had the same question some time ago. It helped me a lot to actually read through the [book](https://github.com/rlabbe/Kalman-and-Bayesian-Filters-in-Python/) @rlabbe wrote.
> 
> I don't have the code handy, but here is the param mapping and the approximate functional implementation (re-check the array shapes). Hope you can figure out the rest. If not – definitely read the book :)
> 
> ```
> from filterpy.kalman import batch_filter
> 
> def kalman_ma_batch(zs, x, P, Q, R=1., F=1., H=1.):
>     """
>     Parameters
>     ----------
>     zs: observations, (x.values in your code)
>     x: initial mean estimate, e.g. = x.values[0]
>     P: initial covariance estimate, e.g. = 1.
>     Q: process noise (transition covariance), tuning parameter
>     R: measurement noise (observation covariance), default = 1.
>     F: transition matrix, default = 1.
>     H: measurement (observation) matrix, default = 1.
>     
>     Returns
>     -------
>     (x_posts, P_posts), same as (state_means, state_covariances) in PyKalman
>     """
>     
>     xs = np.atleast_1d(x)
>     Ps = np.eye(xs.shape[0])*P
>     Fs = np.full(zs.shape[0], F)
>     Qs = np.full(zs.shape[0], Q)
>     Hs = np.full(zs.shape[0], H)
>     Rs = np.full(zs.shape[0], R)
>     
>     x_posts, P_posts, _, _ = batch_filter(xs, Ps, zs, Fs, Qs, Hs, Rs)
>     return x_posts.flatten(), P_posts.flatten()
> ```
> 
> Usage:
> 
> ```
> state_means, _ = kalman_ma_batch(x.values, 0., 1., Q=0.01)
> ```

Thank you for your answer! It really helped me a lot!

**Comment by AlexAtCCRI** [comment]
i would be curious to go the other way (from `filterpy` to `pykalman`) to make use of the EM algorithm.
