### ISSUE TITLE
Did you ever test the 'RadarUKF.py'?

### ISSUE THREAD

**Issue by deepmeng** [rlabbe/filterpy#241]
Did you ever test the 'RadarUKF.py'?
So many errors.

**Comment by rlabbe** [comment]
That's put really rudely. Keep it nice.

**Comment by rlabbe** [comment]
In any case, the readme.md states

> These examples are vastly out of date. Do not use!
> For now look at the code in the test directories. Test code is written to run with py.test on the command line.

**Comment by deepmeng** [comment]
> That's put really rudely. Keep it nice.
Neither attitude nor tone can be clearly seen here. I simply questioned whether there were errors in such a powerful tool. You're just calling me rude? 
However, I am a generous and tolerant man. I still have great respect for your knowledge and achievements. I will also pay attention to my expression and wording when raising questions in the future to avoid unnecessary misunderstandings and troubles.
