### ISSUE TITLE
Issues installing with pip

### ISSUE THREAD

**Issue by gconte75** [rlabbe/filterpy#252]
Doing a -pip install filterpy- or a -python setup.py install- fails due to the package __version__ apparently missing.
It could be something specific to my environment (WIN 10, no conda, I install everything with pip and, for some very recent packages, sometimes manual mods or adjustments are required).  
Anyway, in case anyone reading this book, finds himself facing the same issue, here is what I did.
Mind you, I went for the quickest fix I could find, I wanted to test the code right away.

Here are the changes I applied pre and post install (replace the version string, "1.4.5" with the actual one from the code you downloaded):

<ISSUE1>
[during setup python cannot seem to find the package version and the installation fails right away]

        PRE-INSTALL
	added 
		filterpy.__version__= "1.4.5"
	in file setup.py  (right before setup(...)  )
	
        POST-INSTALL
	added
		__version__= "1.4.5"
	in file __init__.py (in \PYTHON_PATH\Lib\site-packages\filterpy)
	
</ISSUE1>

<ISSUE2>
[discrete_bayes functions cannot be imported: the corresponding folder is not being copied into the lib\site-packages\filterpy folder by the installer]

        POST-INSTALL
	copied over
		discrete_bayes folder (from \GIT_PYTHON_SANDBOX\build\lib\filterpy)
	to 	\PYTHON_PATH\Lib\site-packages\filterpy

</ISSUE2>

**Comment by nilsmelchert** [comment]
If this issue is resolved, could you please close it?
