### ISSUE TITLE
Enhancement - check all matrices and sample y input in KalmanFilter.test_matrix_dimensions()

### ISSUE THREAD

**Issue by boiler42** [rlabbe/filterpy#27]
Currently it looks like test_matrix_dimensions only checks x, P, and Q.  The docs indicate it checks the size of everything, which is misleading since it doesn't check F, H, R, or a sample input.  I would prefer it to check all of those in such a way that the state of the filter is not altered.  Running down mismatched sizes is one of my least favorite things to debug and it could be streamlined.

Said slightly differently, in order to fully check the size of inputs, you need to run it, but in order to run it you need to have (mostly) correct inputs, which results in some awkward circular logic.

I think the signature could be test_matrix_dimensions(sample_input=None), where if sample_input is supplied it is additionally checked.  That would not change the previous api.

Thank you

**Comment by rlabbe** [comment]
I've pushed a fix for this, but have not released a new version yet. 

It's a bit troublesome to test all the possibilities - you can alter the # of measurements, x can be a 1D array or a 2D column vector, etc. I think I handled all the cases, but it is possible that I assert on something that is okay, or don't assert on an error. However, all unit tests pass.

**Comment by boiler42** [comment]
Thank you very much.  

I am a mechanical engineer with python experience.  I would like to use a kalman filter on a structural test of a cantilevered beam with three DOF (2 bending + torsion).  Each is loaded by a hydraulic cylinder.  Cylinder force and displacement is measured.  I would like to get better position, velocity, and acceleration signals plus experimentally estimate stiffness, damping, and mass for each DOF.  The axes are coupled together.  Anyways, with what little I do know about kalman filters, it seems they should do the trick.

Thank you very much for your book.  I really appreciate it.  It is tremendously helpful.  I think its the perfect introductory text.

**Comment by rlabbe** [comment]
That's a very interesting application. I was just reading a paper that used the KF to resolve medical imaging of a heart. but I don't know much about these sorts of applications - I do object tracking in my work. We do do things like derive physical properties, but I am not sure how far I can go given confidentiality agreements. I suggest looking at if you can use the KF to improve the dynamics estimates, and then after you have a collection of that data estimate the physical parameters. Your alternative is to place things like stiffness into your state vector, but the observability might be low. Low observability can push you into singularities. There is theory (which I don't know) that allows you to compute the observability of your system. I recently added a blurb about it to the book - Grewal covers it to a small extent in his KF book, and points you to the original literature.

Also, larger systems like yours tend to use ensemble techniques - the particle filter, condensation filter, the Ensemble filter (which can be viewed as a particle filter, though the formulation is different), and so on. 

Anyway, I'm glad the book helped you get started on this journey.

**Comment by boiler42** [comment]
Going out on a limb, I think your book would benefit from adding some case studies.  Ideally they would include problems outside the domain of motion tracking.  To a mechanical engineer, dynamics and system models almost instinctively mean a spring mass damper.  Estimating stiffness, damping, mass, position, velocity, and acceleration from position and external force measurements for a 1 DOF spring mass damper sounds like a good case study candidate to me.  Anyways, just a thought.

**Comment by rlabbe** [comment]
While I to an extent agree, I am constrained by a few things. First, I don't know the other domains very well. Second, I am in talks with a publisher who is insisting on a page limit that seems rather arbitrary and restrictive. I'll probably have to cut material as it is.  If I do publish on dead trees I can still provide case studies online, as an adjunct to the book. 

On the side I am building my knowledge in things like EM, MCMC, and so on, to be able to better tackle the parameter estimation problem. These problems become high dimensional, and there is no clear answer even in the literature; so far as I can tell it is still a very open problem. But I am kind of babbling here. I'm roughly aware of the issues, but hardly experienced in them.

Zhe Chen has an excellent survey paper "Bayesian Filtering: From Kalman Filtering to Particle Filters, and Beyond. I was looking at it this morning for an unrelated matter, and noticed he includes a simple, two segment robotic arm and discusses some of the issues you are interested in. It is available online:
http://www.dsi.unifi.it/users/chisci/idfric/Nonlinear_filtering_Chen.pdf It won't be enough to solve your problem, but I get the impression it is enough to scope the problem and suggest what to read next.

And that is my biggest goal with the book - get people to the point where they can read the original literature. I fear I have been not quite rigorous enough with the math to make that entirely possible, but there is an unavoidable amount of math somebody needs to learn to access the literature, and I cannot include 3 textbooks of math in my book. That is my conundrum. I am thinking of what my next book will be. It could be some of these math techniques, or more advanced topics in KF. We'll see.
