### ISSUE TITLE
Get filterpy working with conda install

### ISSUE THREAD

**Issue by rlabbe** [rlabbe/filterpy#29]
I tried to get it to work with BinStar (much) earlier, but failed for some reason that I can't recall. But it is absurd to not have it working.

**Comment by veeresht** [comment]
I was able to create conda builds for the pypi release version "0.1.2" and have uploaded to my binstar account. The following command should work on all conda supported platforms. 

`conda install -c veeresht filterpy=0.1.2`

I think you forgot to do `conda skeleton pypi --version 0.1.2 filterpy` before doing `conda build .` based on your comments in [conda_install.txt](https://github.com/rlabbe/filterpy/blob/master/conda/conda_install.txt)

This solves the issue.

**Comment by rlabbe** [comment]
Thanks, I have made this change in my instructions and installation and it seemed to work fine with the new 0.1.3 release.
