### ISSUE TITLE
Covariance matrix not positive definite

### ISSUE THREAD

**Issue by MRoobeek89** [rlabbe/filterpy#31]
For some reason, the covariance matrix in my system gets entries that are not positive definite.
Do you have any ideas on what may be causing this issue?

Thanks in advance!

**Comment by jaja3721** [comment]
I got this problem few days ago. I hope someone will answer this question.

**Comment by rlabbe** [comment]
I don't know what your code looks like, or what problem you are trying to solve, so it is impossible to give an exact answer.

In general though, even if your math is perfect, in the end we are linearizing a nonlinear system, and errors will accrue. In practice you need to do a few things:

1) P = 0.5 P + 0.5P^T. This ensures the matrix is symmetric.

2) P = P + eI, where e is some very small number, and I is the identity matrix. This ensures you don't underflow. there is some content in wikipedia on the condition number of a matrix: https://en.wikipedia.org/wiki/Condition_number

**Comment by peter-moran** [comment]
I am also having this issue.

I am using the UKF with a constant velocity model to track the position and orientation of a tag that I get x,y,z,r,p,ya measurements from an external CV library. I am simply trying to handle the non-linearity of angles (for now) as I was able to get a linear filter to work.

While I am not 100% it is the root of the problem, I am finding that the predict step is producing perfectly symmetric P matrices, while the update step does not, with `P - P.T` returning discrepancies along the line of 10^-35. Attempts to correct this with `P = 0.5 P + 0.5P^T` do not work either.

Can anyone give any help? I am looking into this further.

**Comment by peter-moran** [comment]
Never mind that. I forced a symmetric matrix by copying the upper triangle to the lower triangle and still had not positive definite P matrices.
    
    # force P to be symmetric
    self.P = np.triu(self.P) + np.triu(self.P, 1).T

Ultimately, I started commenting things out until I had a very basic UKF and determined that my method for choosing Q was causing the problem. I'm not sure why, bet here is the faulty part below. It did work on my linear filter.

        xy_white_noise = Q_continuous_white_noise(2, dt=dt, spectral_density=np.square(2))
        rot_white_noise = Q_continuous_white_noise(2, dt=dt, spectral_density=np.square(np.pi))
        self.Q[0:2, 0:2] = xy_white_noise  # x, dx
        self.Q[0:2, 0:2] = xy_white_noise  # x, dx
        self.Q[2:4, 2:4] = xy_white_noise  # y, dy
        self.Q[4, 4] = xy_white_noise[0, 0] / 2  # z

Now I got:

        translation_vel_var = 2  # meters/second of variance in prediction accumulated per second
        rotation_vel_var = np.pi/2  # radians/second of variance in prediction accumulated per second
        xyz_white_noise = Q_discrete_white_noise(2, dt=dt, var=translation_vel_var)
        rot_white_noise = Q_discrete_white_noise(2, dt=dt, var=rotation_vel_var)
        self.Q[0:2, 0:2] = xyz_white_noise  # x, dx
        self.Q[0:2, 0:2] = xyz_white_noise  # x, dx
        self.Q[2:4, 2:4] = xyz_white_noise  # y, dy
        self.Q[4, 4] = xyz_white_noise[0, 0]  # z
        self.Q[5, 5] = rot_white_noise[0, 0]  # roll
        self.Q[6, 6] = rot_white_noise[0, 0]  # pitch
        self.Q[7:9, 7:9] = Q_discrete_white_noise(2, dt=dt, var=rotation_vel_var*2)  # yaw, dyaw

and everything works fine. Maybe my variances were too large?
