### ISSUE TITLE
Install behind proxy

### ISSUE THREAD

**Issue by wbatzle** [rlabbe/filterpy#33]
I am trying to install filterpy behind a proxy. The security team will not allow it through the proxy. Any help is appreciated.

**Comment by rlabbe** [comment]
You can download directly from pypi: https://pypi.python.org/pypi/filterpy/0.1.2

or you can checkout from github (this repository).

**Comment by wbatzle** [comment]
We were able to download it but when running the install command we get an error stating that there was an issue with the proxy. Any ideas?

**Comment by rlabbe** [comment]
I really have no idea. Googling suggests a bunch of workarounds in this thread:

http://stackoverflow.com/questions/14149422/using-pip-behind-a-proxy

**Comment by wbatzle** [comment]
Ok so I have more details on this. Using the link you provided didn't help much because that part is working. What is not working is that the install is looking for something else to download which we explicitly block. I am having him download it now and will let you know what happens next. I may have missed the info for this in the requirements section. If not then I would suggest putting it in for those that do not have the ability to download stuff.

  Could not find a version that satisfies the requirement mock (from matplotlib->filterpy) (from versions: )
No matching distribution found for mock (from matplotlib->filterpy)

**Comment by rlabbe** [comment]
I see. setup.py has the line:

    install_requires=['numpy', 'scipy', 'matplotlib'],

This means that it will try to install numpy, scipy, and matplotlib if they are not already installed. 

I don't think I can really distribute matplotlib with my package. There are many different versions, for one thing. I suggest trying to install matplotlib yourself, first. If it is already installed (as well as numpy and scipy) then something else is going on.

**Comment by wbatzle** [comment]
I would suggest adding it as a pre-req in the description somewhere. That way when someone like me has to download it for someone that needs it installed. We can download the pre-reqs with it. No need to package it in yours.

**Comment by rlabbe** [comment]
From the readme:


Requirements
------------

This library uses NumPy, SciPy, Matplotlib, and Python.
