### ISSUE TITLE
package missing from conda channel?

### ISSUE THREAD

**Issue by KenHollandWHY** [rlabbe/filterpy#39]
conda install -c rlabbe filterpy doesnt find filterpy.

**Comment by veeresht** [comment]
Hi @KenHollandWHY, 

The package is available on my conda channel, 
`conda install -c veeresht filterpy=0.1.2`

Refer #29 for more details.

**Comment by rlabbe** [comment]
I've installed the newest version 0.1.3 to conda. following the changes in #29.
