### ISSUE TITLE
multivariate_gaussian incorrect if covariance not np.array

### ISSUE THREAD

**Issue by dmopalmer** [rlabbe/filterpy#40]
`stats.multivariate_gaussian(x,mu,cov)` silently gives the wrong value if cov is, e.g., a list of lists instead of a numpy array.  The failure occurs during the call to _to_cov where the covariance should be checking whether x is a scalar, but is instead checking whether it is not an np.array.

This problem demonstrates itself in the `05-Multivariate-Gaussians` chapter of your book, where putting in a non-diagonal covariance for the 3-d plot gives an orthogonal rather than slanted gaussian.  Changing the covariance list-of-lists to an np.array fixes the problem.

Example:

```
import numpy as np
from filterpy import stats
from scipy.stats import multivariate_normal
np.set_printoptions(precision=3)
mean=(0,0)

cov=[[1,.5],[.5,1]]
print("For list and np.array covariances:")
for covariance in (cov,np.asarray(cov)):
    a = [[stats.multivariate_gaussian((i,j),mean,covariance)
          for i in (-1,0,1)]
         for j in (-1,0,1)]
    print(np.asarray(a))
    print()
```
Gives two different results for the datatypes of the covariance:
```
For list and np.array covariances:
[[ 0.059  0.097  0.059]
 [ 0.097  0.159  0.097]
 [ 0.059  0.097  0.059]]

[[ 0.094  0.094  0.025]
 [ 0.094  0.184  0.094]
 [ 0.025  0.094  0.094]]
```

**Comment by rlabbe** [comment]
Thank you. I've checked in a fix. I haven't created a new release yet (it will be version 0.1.3, but I will soon.
