### ISSUE TITLE
conda install issue

### ISSUE THREAD

**Issue by pjvalla** [rlabbe/filterpy#42]
I am on a Mac version 10.11.6 .  This is the output of running your conda command:

```
Phil@MacBook-Pro~/anaconda/envs $ conda install -c rabbi filterpy
Fetching package metadata: ......
Solving package specifications: .
Error:  Package missing in current osx-64 channels: 
  - filterpy

You can search for this package on anaconda.org with

    anaconda search -t condo filterpy
```

**Comment by vwrobel** [comment]
Same here. I switch to pip.

**Comment by peer23peer** [comment]
Same her on windows 7:

`PackageNotFoundError: Package not found: '' Package missing in current win-64 channels:
 - filterpy`

**Comment by rlabbe** [comment]
I suppose I should look at this. pip works fine, though. At the time I didn't find the instructions for adding a package to conda particularly clear. If someone knows how to do this I welcome help.....

**Comment by hajapy** [comment]
@rlabbe: would you be interested in having FilterPy be built and distributed on conda-forge? If you are not familiar with it, have a look at https://conda-forge.github.io/

I can assist in getting this set up if it's not something you have time/interest in doing.

**Comment by hajapy** [comment]
I began making a recipe here: https://github.com/hajapy/staged-recipes/tree/hajapy/filterpy

There seem to be some issues that need addressing before I can open a PR with passing builds. 

1. https://github.com/rlabbe/filterpy/blob/master/MANIFEST.in#L2 
Points to a non-existent file

2. https://github.com/rlabbe/filterpy/blob/master/setup.py#L83 
Also points to this non-existent file

3. https://github.com/rlabbe/filterpy/blob/master/setup.py#L63
Does filterpy really not support py 3.6? Conda-forge will by default build 2.7, 3.5 and 3.6. If it's not 3.6 compatible we would need to disable those builds, but I suspect it works fine under 3.6

**Comment by hajapy** [comment]
Turns out another issue is that those minor errors meant that the LICENSE file was not included in the tar file uploaded to pypi. 

Have a look at https://pypi.io/packages/source/f/filterpy/filterpy-0.1.5.tar.gz, there is no LICENSE file in it.

**Comment by hajapy** [comment]
[Opened PR on conda-forge/staged-recipes](https://github.com/conda-forge/staged-recipes/pull/3145). Had to include a patch for the LICENSE file issue where I simply create the file prior to the build. Future versions of the recipe could remove this patch if the pypi archive contains the LICENSE file.

**Comment by rlabbe** [comment]
It appears that the name I used is LICENSE, not LICENSE.txt. LICENSE is checked into the repository.

**Comment by rlabbe** [comment]
As far as conda-forge goes, it is not clear to me what the benefit/costs are. To be honest I've found supporting PyPi to be quite a pain. I've googled a bit - a blob on continuum.io suggests that conda-forge is for trusted binary packages. Mine is purely source. 

I'm not against it if it is useful to people, but I can't say I am interested in significant increase in support/workload. 

Also, it is essentially mature now. I would suggest bumping version number to 1.0, and changing the classifier in setup.py to 5 - Production/Stable

**Comment by rlabbe** [comment]
Also, it runs in 3.6. The setup.py seems overly specific to me - I don't want to have to update that file every time a new version of Python comes out. Would it make sense to just list 2.7, and then 3?
        'Programming Language :: Python :: 2.7',
        'Programming Language :: Python :: 3',

As you may be able to tell, I don't do much in the broader Python community - the specifics of a lot of these tools are not well known to me. I did _just enough_ to get it working for PyPi and then left it alone.

**Comment by hajapy** [comment]
> As far as conda-forge goes, it is not clear to me what the benefit/costs are. To be honest I've found supporting PyPi to be quite a pain. I've googled a bit - a blob on continuum.io suggests that conda-forge is for trusted binary packages. Mine is purely source.

Putting your package in conda-forge would help out a user such as myself that depends on many  scientific python libraries built from source and wants to manage an environment entirely with conda as opposed to a mixture of conda and pip. To me this is important because of the conda package requirement solver which ensures environments do not have conflicts. 

In terms of added support, maintaining a source-only recipe on conda-forge is relatively little work: update a version number and the sha256 for the pypi archive. For this little work you get packages distributable on all 3 major platforms and installable into conda environments along with the other big scientific libraries. If you had more complex requirements, such as numba, you could provide them with conda. 

Of course, if you do not want want to be a maintainer I can remove you from the list and be the sole maintainer for now. The aforementioned fixes should be brought to this repo anyway and an updated pypi distribution could be published.

**Comment by hajapy** [comment]
Linux packages are ready now (other platforms to follow shortly). 
`conda install -c conda-forge filterpy` should now work 
Here's the filterpy-feedstock: https://github.com/conda-forge/filterpy-feedstock
And here are the files hosted on anaconda.org: https://anaconda.org/conda-forge/filterpy/files

**Comment by hajapy** [comment]
@pjvalla @rlabbe this issue can be closed now. Any further issues with conda installation should be directed to the feedstock at: https://github.com/conda-forge/filterpy-feedstock

**Comment by rlabbe** [comment]
Thanks for all of your help!
