### ISSUE TITLE
EKF predict, parameter u not used

### ISSUE THREAD

**Issue by oxinabox** [rlabbe/filterpy#5]
In 
https://github.com/rlabbe/filterpy/blob/7c3a683104e07d42f73e9a739a07549389cd67bf/filterpy/kalman/EKF.py

the `predict` function takes a parameter `u`
it fails to pass this forward to the `predict_x` function.

Starting on line 161:
```
 def predict(self, u=0):
      """ Predict next position.
      **Parameters**
      u : np.array
      Optional control vector. If non-zero, it is multiplied by B
      to create the control input into the system.
      """
      self.predict_x()
      self._P = dot3(self._F, self._P, self._F.T) + self._Q
```

Should read:

```
 def predict(self, u=0):
      """ Predict next position.
      **Parameters**
      u : np.array
      Optional control vector. If non-zero, it is multiplied by B
      to create the control input into the system.
      """
      self.predict_x(u)
      self._P = dot3(self._F, self._P, self._F.T) + self._Q
```

The use of `u` has not come up in the book, yet (to my knowledge).
(But when it does, this could be a confusing bug).

I could submit a pull request for this, but it seems a bit much for a single character change.

**Comment by rlabbe** [comment]
Thanks, excellent catch. I have pushed this change to github, along with a few other minor changes. I have not updated PyPi repository yet, so you will have to install from github, not Pypi, if using pip to install.

For those interested, B and u are not covered in the book (yet). They are used when we know we have a control input into a system, such as steering commands to a robot. All my experience is with passive tracking, so I need to test and develop this more before I start writing about it. Sebastian Thrun's udacity course touches on it if you are looking for open source material about it.
