### ISSUE TITLE
Comments for filterpy.stats.multivariate_multiply()

### ISSUE THREAD

**Issue by esvhd** [rlabbe/filterpy#54]
In the method signature, comments for parameter `c1` and `c2` currently say they are the `means` of the respective Gaussian. Should they not be `covariance` instead?

Happy to start a PR if that's the case.

Thanks.

**Comment by rlabbe** [comment]
Thanks! I've fixed and pushed a correction.

**Comment by esvhd** [comment]
Fantastic, thanks!
