### ISSUE TITLE
No posterior estimator for IMMEstimator?

### ISSUE THREAD

**Issue by KevinnnnMa** [rlabbe/filterpy#60]
Hi,
After carefully reading your source code for IMMEstimator class in filterpy.kalman, my understanding is that  after running the update() function, 
self.x = \hat{x_{k+1|k}}, that is, the prediction(prior estimate) for time k+1 at time t. This is also the case for each individual filter.
I wonder what if i want to get \hat{x_{k|k}}, i.e., the posterior estimate of x, as well as P, at time k ?

**Comment by KevinnnnMa** [comment]
it seems that you calculate posterior estimates as intermediate steps, which are overwritten by later steps in the update() function

**Comment by rlabbe** [comment]
Sorry this took so long. Fixed and released in version 1.4.4
