### ISSUE TITLE
No example for use of EKF

### ISSUE THREAD

**Issue by drssdinblck** [rlabbe/filterpy#63]
Hi,

I wanted to use your EKF for a project of my own, but I cannot figure out how to set the variables and matrices, because there is no example provided.

**Comment by rlabbe** [comment]
Hi, I acknowledge the documentation is unacceptably sparse. However, this project was developed in support of my book, and that is full of examples.

https://github.com/rlabbe/Kalman-and-Bayesian-Filters-in-Python

**Comment by rlabbe** [comment]
I've added a link to the book in most of the classes.

I'll close this, despite the documentation being not up to snuff, as this is very specific to one user and class, and I'd rather have more generalized issues to check in against.
