### ISSUE TITLE
Problem while implementing Kalman Filter

### ISSUE THREAD

**Issue by aeyuxi** [rlabbe/filterpy#66]
Hi, I have created a dictionary of Kalman Filters. I'm having an issue in the update function. 
`
AssertionError: shape of z should be (), but it is (1,)
`
I have a 1D Kalman Filter, here it is the declaration. 

```
K = KalmanFilter (dim_x=1, dim_z=1)
#State space model used
K.F= np.array([1.])
 #Initial State
K.x=np.array([-60.])                          
#Measurement Matrix                         
K.H=np.array([1.])
#Covariance Matrix
K.P=np.array([10.])
#Process Noise          
K.Q=np.array([20.])                              
#Measurement Noise
K.R=np.array([0.002])
#Add KF to the dictionary when a new UUID is detected
KF_dict.update({data:K})
```

Hope you can help me, thanks.

**Comment by rlabbe** [comment]
Hi, all of your KF matrices need to be 2 dimensional, and the measurement needs to be 1 dimensional, like so:


```python 
from filterpy.kalman import KalmanFilter
import numpy as np

K = KalmanFilter (dim_x=1, dim_z=1)
K.F= np.array([[1.]])
K.x=np.array([[-60.]])                          
K.H=np.array([[1.]])
K.P=np.array([[10.]])
K.Q=np.array([[20.]])                              
K.R=np.array([[0.002]])


K.update([3.])

**Comment by rlabbe** [comment]
If you drew an example from code that used 1D arrays, please let me know; I used to support that, but it became more trouble than it was worth and didn't work at all with other modules such as the UKF. So now all need to follow the rules above. If old style code is hanging around somewhere in my codebase I want to delete it immediately so it doesn't mislead others.

**Comment by aeyuxi** [comment]
I'm trying to do 1-dimensional KF with one measurement and one estimate. So, it doesn't support that? 
Would it be possible to add it?. 

I tried to implement the KF that you have as an example, and it works. However. I tried to tweak the parameters, but the KF is responding very slowly. I tried to play with Q and R. Increasing Q and decreasing R, so I could have a better response. However, it didn't work.

**Comment by rlabbe** [comment]
I mean the numpy arrays have to be 2D, regardless of the dimensionality of the state. The state can be 1, 2, 3, or 3 billion, and the numpy arrays need to be 2D.

For example, you wrote:
```python 
K.F= np.array([1.])
```

whereas it has to be
```python
K.F= np.array([[1.]])
```

**Comment by aeyuxi** [comment]
Got it to work. However, I'm trying to tweak the parameters of R and Q, I don't see any difference in the response of the filter. Do you know why? 

[https://drive.google.com/open?id=0B6u84QEUGqGYeXZFWEJvN0RQekE](url)

**Comment by aeyuxi** [comment]
Nevermind. Got it working. 

Note to self: When calling predict. Do not forget ()
