### ISSUE TITLE
Issue running Kalman Filter

### ISSUE THREAD

**Issue by ayush1997** [rlabbe/filterpy#72]
Hi I was trying out Kalman filter and having some issues with update().
`AssertionError: shape of z should be (1, 1), but it is (2, 1)`

This is what the  filter looks like.
```
f = KalmanFilter (dim_x=2, dim_z=1)
f.x = np.array([[0.88],[850]]) 
f.F = np.array([[1.,1.],[0.,1.]])
f.H = np.array([[1.,0.]])
f.P = np.array([[1000.,0.],[ 0., 1000.] ])
f.R=np.array([[0.002]])
from filterpy.common import Q_discrete_white_noise
f.Q = Q_discrete_white_noise(dim=2, dt=0.1, var=0.13)
f.predict()
f.update(np.array([ [a] ,[b] ] ))
```

Thanks.

**Comment by rlabbe** [comment]
You designed the KF to have a z dimension of 1 (dim_z=1), but are passing in a 2x1 array. I have no idea what a and b are in your code, so I cannot opine further,  but if you have 2 measurements you need to design the KF differently.

**Comment by ayush1997** [comment]
Thanks for the response.
I will need to redesign it again,I have 2 measurements.
Thanks again.
