### ISSUE TITLE
delete the stupid dot3 type functions

### ISSUE THREAD

**Issue by rlabbe** [rlabbe/filterpy#74]
They are non-standard, and will eventually be supplanted by @ once I move to Python 3.5+.

**Comment by rlabbe** [comment]
Done.

**Comment by FerPapi** [comment]
Hello, I had to reinstall filterpy and I was using the dot3 function. Which function is its replacement?

**Comment by rlabbe** [comment]
Sorry, it never occured to me that somebody would be using these functions.

It is just a concatenation of .dot. 

dot3(A,B,C) => dot(dot(A, B), C)

that is safer than A.dot(B).dot(C) in case any of A, B, or C are not of type array. the dot function can accept scalars, for example, so if A=3, the latter will raise an exception since int does not implement .dot member function.

**Comment by FerPapi** [comment]
Thanks. I was more focused on the higher level stuff (like, will this kalman filter help solve my problem) rather than focusing on specific functions. Thanks for the quick reply, though.
