### ISSUE TITLE
problem with Q matrix

### ISSUE THREAD

**Issue by chaowu2009** [rlabbe/filterpy#83]
Q_discrete_white_noise(dim, dt=dt, var=0.1)

It seems you only allow dim =2 or dim =3.

**Comment by rlabbe** [comment]
Are you really doing constant jerk or higher filters?

**Comment by Prokhozhijj** [comment]
I want to join to the request of chaowu2009. It would be great to have ability to track highly maneuvering targets with Kalman filters.
Maybe following documents you consider as useful if you decide to implement this feature.
Thanks.

[https://core.ac.uk/download/pdf/11603388.pdf](url)

[https://www.researchgate.net/profile/Dr_Vps_Naidu2/publication/44939740_Evaluation_of_Acceleration_and_Jerk_Models_in_Radar_andIRST_Data_Fusion_for_Tracking_Evasive_Maneuvering_Target/links/0912f50619f3b044e7000000/Evaluation-of-Acceleration-and-Jerk-Models-in-Radar-and-IRST-Data-Fusion-for-Tracking-Evasive-Maneuvering-Target.pdf](url)

**Comment by rlabbe** [comment]
I've pushed a commit, I'll be doing a formal release in the next day or so.

**Comment by rlabbe** [comment]
Released in 1.2.4
