### ISSUE TITLE
Probably bug in batch_filter function from hinfinity_filter.py

### ISSUE THREAD

**Issue by Prokhozhijj** [rlabbe/filterpy#88]
File "C:\Python36\lib\site-packages\filterpy\hinfinity\hinfinity_filter.py", line 195, in batch_filter
    self.update(z,r)
TypeError: update() takes 2 positional arguments but 3 were given

**Comment by rlabbe** [comment]
I am not sure of the fix here. Is V truly the equivalent of R in the Kalman filter. In any case, there is a clear nomenclature bug; batch_update() should not take Rs, but Vs if we are going to do this. 

I've grown unhappy with my batch_filter functions in any case; they discard a lot of info (S, K, y, etc) to let the user avoid writing a for loop. I'm not going to make a decision on this broader issue at the moment.

**Comment by rlabbe** [comment]
Fixed.
