### ISSUE TITLE
kalman filter P update

### ISSUE THREAD

**Issue by 6ry** [rlabbe/filterpy#9]
in file kalman_filter.py, line 174-176, you implemented the following ...
174         # P = (I-KH)P(I-KH)' + KRK'
175         I_KH = self._I - dot(K, H)
176         self._P = dot3(I_KH, P, I_KH.T) + dot3(K, R, K.T)

this is mathematically correct, yet line 176 could be further reduced to ...
self._P = dot(I_KH, P)

because (cf. Simon's book p128, eq 5.16)
P = (I-KH)P(I-KH)' + KRK' = (I-KH)P

**Comment by rlabbe** [comment]
please refer to issue 7, it explains the reason for this form oh the equation.

https://github.com/rlabbe/filterpy/pull/7

In short, it is numerically stable compared to the reduced form.

**Comment by 6ry** [comment]
thank you for the explanation.
