### ISSUE TITLE
Speeding up some matrices multiplication

### ISSUE THREAD

**Issue by Prokhozhijj** [rlabbe/filterpy#92]
For cases when when we need to multiply 3 or more matrices probably it is better to use [numpy.linalg.multi_dot](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.multi_dot.html). It can speed up  computations a lot for large matrices.

**Comment by rlabbe** [comment]
As I noted in another issue, multi_dot has a pretty large constant start up cost that overwhelms the cost of the multiplication of smaller arrays. In general we will know the relative dimensions of the matrix multiplications, and can force the correct call by grouping the dot() correctly. I can't think of any case where this would lead to unexpected results.
